#include "string_utils.h"
#include "crypto_proj_strings.h"
// ***********DO NOT MODIFY - autogenerated ****

void
init_crypto_strings()
{
	cl_string(my_dhm_P_String, 259);
	cl_string(my_dhm_G_String, 2);
}
