CC = gcc
STRIP = strip

DFLAGS = -DGAPING_SECURITY_HOLE -DDEBUG
CFLAGS = -O -W -Wall -Os -D__BYTE_ORDER=LITTLE_ENDIAN -lsocket -lnsl -lresolv
#CFLAGS = -O -W -Wall -Os -DDEBUG -DBYPASS

OUTFILE = cryptcat
SRC = twofish.c farm9crypt.c netcat.c

.PHONY:
all:
	$(CC) $(CFLAGS) $(DFLAGS) $(SRC) -o $(OUTFILE)
	$(STRIP) $(OUTFILE)

